In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pickle as pickle

%matplotlib inline

# Paper figures

In [2]:
CI_list = []

with open('grad_checks_FC_KFAC/batch128/ptb_var_flip.pkl','rb') as f:
    Fg_CI = pickle.load(f)
with open('grad_checks_FC_KFAC/batch128/ptb_var_pert.pkl','rb') as f:
    NFg_CI = pickle.load(f)
CI_list.append((Fg_CI,NFg_CI))

with open('grad_checks_FC_KFAC/batch256/ptb_var_flip.pkl','rb') as f:
    Fg_CI = pickle.load(f)
with open('grad_checks_FC_KFAC/batch256/ptb_var_pert.pkl','rb') as f:
    NFg_CI = pickle.load(f)
CI_list.append((Fg_CI,NFg_CI))

with open('grad_checks_FC_KFAC/batch512/ptb_var_flip.pkl','rb') as f:
    Fg_CI = pickle.load(f)
with open('grad_checks_FC_KFAC/batch512/ptb_var_pert.pkl','rb') as f:
    NFg_CI = pickle.load(f)
CI_list.append((Fg_CI,NFg_CI))

with open('grad_checks_FC_KFAC/batch1024/ptb_var_flip.pkl','rb') as f:
    Fg_CI = pickle.load(f)
with open('grad_checks_FC_KFAC/batch1024/ptb_var_pert.pkl','rb') as f:
    NFg_CI = pickle.load(f)
CI_list.append((Fg_CI,NFg_CI))

with open('grad_checks_FC_KFAC/batch2048/ptb_var_flip.pkl','rb') as f:
    Fg_CI = pickle.load(f)
with open('grad_checks_FC_KFAC/batch2048/ptb_var_pert.pkl','rb') as f:
    NFg_CI = pickle.load(f)
CI_list.append((Fg_CI,NFg_CI))

with open('grad_checks_FC_KFAC/batch4096/ptb_var_flip.pkl','rb') as f:
    Fg_CI = pickle.load(f)
with open('grad_checks_FC_KFAC/batch4096/ptb_var_pert.pkl','rb') as f:
    NFg_CI = pickle.load(f)
CI_list.append((Fg_CI,NFg_CI))


ValueError: unsupported pickle protocol: 3

[array([  2.43579739e-08,   2.84215073e-08,   2.31353333e-08,
          2.46478140e-08,   2.69877165e-08,   2.13274138e-08,
          2.79806497e-08,   2.17211968e-08,   2.53372466e-08,
          2.74530527e-08]),
 array([  3.77512034e-08,   4.29482536e-08,   3.55471383e-08,
          3.77850248e-08,   4.13492336e-08,   3.31032998e-08,
          4.27096534e-08,   3.38651782e-08,   3.88836538e-08,
          4.14621808e-08]),
 array([  2.56822944e-07,   2.96834840e-07,   2.42711425e-07,
          2.59562281e-07,   2.83042993e-07,   2.26148391e-07,
          2.94479858e-07,   2.31034802e-07,   2.67799636e-07,
          2.87837708e-07]),
 array([  3.85928743e-08,   4.41329043e-08,   3.64746682e-08,
          3.90640348e-08,   4.24130493e-08,   3.43850881e-08,
          4.38460953e-08,   3.50483185e-08,   4.03779078e-08,
          4.30047164e-08])]

In [1]:
mini_batch = [128,256,512,1024,2048,4096]

non_flip_mean = [[], [], [], [], [], [], []]
non_flip_CI_low = [[], [], [], [], [], [], []]
non_flip_CI_high = [[], [], [], [], [], [], []]

flip_mean = [[], [], [], [], [], [], []]
flip_CI_low = [[], [], [], [], [], [], []]
flip_CI_high = [[], [], [], [], [], [], []]

t_49 = 1.684
t_10 = 1.812

for i in range(7):  # i = 0, 1, 2, 3, 4, 5, 6
    for (Fg_var, NFg_var) in CI_list:
        flip_mean[i].append(Fg_var[i].mean())
        flip_CI_low[i].append(Fg_var[i].mean() - np.std(Fg_var[i], ddof=1) * t_10/np.sqrt(10))  # Critical: what is t_49? and we don't have 50 samples...
        flip_CI_high[i].append(Fg_var[i].mean() + np.std(Fg_var[i], ddof=1) * t_10/np.sqrt(10))

        non_flip_mean[i].append(NFg_var[i].mean())
        non_flip_CI_low[i].append(NFg_var[i].mean() - np.std(NFg_var[i], ddof=1) * t_10/np.sqrt(10))
        non_flip_CI_high[i].append(NFg_var[i].mean() + np.std(NFg_var[i], ddof=1) * t_10/np.sqrt(10))

F_errorbars = [[], [], [], [], [], [], []]
NF_errorbars = [[], [], [], [], [], [], []]

for i in range(7):
    F_errorbars[i] = [np.array(flip_mean[i]) - np.array(flip_CI_low[i]), np.array(flip_CI_high[i]) - np.array(flip_mean[i])]
    NF_errorbars[i] = [np.array(non_flip_mean[i]) - np.array(non_flip_CI_low[i]), np.array(non_flip_CI_high[i]) - np.array(non_flip_mean[i])]
    
flip_labels = ['W1-Flip', 'W2-Flip', 'W3-Flip', 'W4-Flip', 'W5-Flip', 'W6-Flip', 'W7-Flip']
nonflip_labels = ['W1_NoFlip', 'W2-NoFlip', 'W3-NoFlip', 'W4-NoFlip', 'W5-NoFlip', 'W6-NoFlip', 'W7-NoFlip']

colors = ['b', 'r', 'y', 'g', 'c', 'm', 'k']

for i in range(7):
    plt.errorbar(mini_batch, flip_mean[i], yerr=F_errorbars[i], label=flip_labels[i], color=colors[i])
    plt.errorbar(mini_batch, non_flip_mean[i], yerr=NF_errorbars[i], label=nonflip_labels[i], color=colors[i], linestyle=':')

plt.xscale('log')
plt.yscale('log')
plt.xlabel('batch size')
plt.ylabel('variance')
lgd = plt.legend(bbox_to_anchor=(0., 1.12, 1., 1.12), loc=3,
           ncol=3, mode="expand", borderaxespad=0.)
plt.title("Variance Estimation")
# plt.savefig('BBbvariance.png', bbox_extra_artists=(lgd,), bbox_inches='tight')
# plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
plt.show()

'mini_batch = [16,128,256,512,1024,2048,4096]\n\nnon_flip_mean = [[], [], [], []]\nnon_flip_CI_low = [[], [], [], []]\nnon_flip_CI_high = [[], [], [], []]\n\nflip_mean = [[], [], [], []]\nflip_CI_low = [[], [], [], []]\nflip_CI_high = [[], [], [], []]\n\nt_49 = 1.684\nt_10 = 1.812\n\nfor i in range(4):  # i = 0, 1, 2, 3\n    for (Fg_var, NFg_var) in CI_list:\n        flip_mean[i].append(Fg_var[i].mean())\n        flip_CI_low[i].append(Fg_var[i].mean() - np.std(Fg_var[i], ddof=1) * t_10/np.sqrt(10))  # Critical: what is t_49? and we don\'t have 50 samples...\n        flip_CI_high[i].append(Fg_var[i].mean() + np.std(Fg_var[i], ddof=1) * t_10/np.sqrt(10))\n\n        non_flip_mean[i].append(NFg_var[i].mean())\n        non_flip_CI_low[i].append(NFg_var[i].mean() - np.std(NFg_var[i], ddof=1) * t_10/np.sqrt(10))\n        non_flip_CI_high[i].append(NFg_var[i].mean() + np.std(NFg_var[i], ddof=1) * t_10/np.sqrt(10))\n\nF_errorbars = [[], [], [], []]\nNF_errorbars = [[], [], [], []]\n\nfor i in r